[mypy]
plugins = mypy_django_plugin.main
ignore_missing_imports = True
check_untyped_defs = True

[mypy.plugins.django-stubs]
django_settings_module = facial_recon.settings

[mypy-*.migrations.*]
ignore_errors = True
