# Generated by Django 5.0.1 on 2024-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
