# Generated by Django 5.0.1 on 2024-02-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='citizen_images',
            new_name='CitizenImage',
        ),
        migrations.RenameModel(
            old_name='Incidents',
            new_name='Incident',
        ),
    ]
