# Generated by Django 5.0.1 on 2024-04-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incident_vehicle_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
