# Generated by Django 5.0.1 on 2024-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_citizen_images_citizenimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
