# Generated by Django 5.0.1 on 2024-02-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incident_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizenimage',
            name='image',
            field=models.ImageField(upload_to='citizen/images/'),
        ),
    ]
