# Generated by Django 5.0.1 on 2024-04-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='points',
            new_name='maximum_points_threshold',
        ),
    ]
