# Generated by Django 5.0.1 on 2024-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incident_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
